apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T07:20:26Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4972"
  uid: 0a71f844-c0cc-452a-833e-88112fca322c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.219.226
  clusterIPs:
  - 10.108.219.226
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30816
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
